databases:
  - name: mysite
    databaseName: mysite
    user: mysite

 services:
 - type: pserv
   name: pgbouncer
   runtime: docker
   plan: standard
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: mongodb+srv://pranjal:pranjal123@cluster0.inffm46.mongodb.net/?retryWrites=true&w=majority
     fromDatabase:
       name: mysite
       property: connectionString
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: pserv
    name: pgbouncer
    runtime: docker
    plan: standard
    repo: https://github.com/render-oss/docker-pgbouncer
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50

     fromDatabase:
       name: mysite
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50